server:
  tomcat:
    threads:
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /time
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/timesync?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 2
      max-active: 4
      min-idle: 2
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  data:
    mongodb:
      host: localhost
      port: 27017
      database: timeSync
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 3120793223@qq.com
    password: rdwohqwtxxpudfge
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.timeSync.www.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    com.timeSync.www.mapper: warn
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"
time-sync:
  jwt:
    secret: timeSyncApp_fishx_123456
    expire: 5
    cache-expire: 10
  email:
    system: 3120793223@qq.com
  face:
    createFaceModelUrl: http://192.168.44.128:3000/create_face_model
    checkinUrl: http://192.168.44.128:3000/checkin
  image-folder: C:\Users\Administrator\Desktop
  code: BF3BDB86B2CE23EE
  recieveNotify: http://loaclhost:8080/emos-wx-api/meeting/recieveNotify
wx:
  app-id: wx30d73d97e0d55aca
  app-secret: 10a44b0864593259533e0e6d05fa3b16

emos:
  jwt:
    secret: abc123456
    expire: 5 #过期时间（天）
    cache-expire: 10 #缓存过期时间(天)
  face:
    createFaceModelUrl: http://192.168.92.128:3000/create_face_model
    checkinUrl: http://192.168.92.128:3000/checkin
  image-folder: C:\Users\Administrator\Desktop
  code: BF3BDB86B2CE23EE
  recieveNotify: http://loaclhost:8080/emos-wx-api/meeting/recieveNotify
workflow:
  url: http://192.168.92:9090/emos-workflow
trtc:
  appid: 1600003181
  key: a48856884029dc2fb1525019422edcc1be020b687e47844bf368541a4c0496cf
  expire: 86400
oss:
  qiniu:
    url: http://s0c9hhw99.hn-bkt.clouddn.com # 这里如果有自己的域名就去绑定自己的 没有的就只能使用七牛云的测试域名
    accessKey: JbgaOsYLpkkpG0nCEyRzyQlLOSepwljQ7OYgWm0Y #公钥
    secretKey: babQTm0kWBCXJ3f7awo2y17TOMYeJsDRdqYKynzK #私钥
    bucketName: emos-wx-image #控件名称